version: 2

dependencies:
  pre:

jobs:
  build:

    docker:
      - image: quay.io/fenicsproject/stable:2019.1.0.r3
        user: fenics
        environment:
          LD_LIBRARY_PATH: /home/fenics/local/lib
          CMAKE_PREFIX_PATH: /home/fenics/local
    working_directory: /home/fenics/xalbrain

    steps:
      - checkout

      - run:
          name: install-python-requirements
          command: |
            sudo python3 -m pip install --upgrade pip
            sudo python3 -m pip install pytest --upgrade
            sudo python3 -m pip install pytest-xdist
            sudo python3 -m pip install git+git://github.com/jakobes/xalode

      - run:
          name: Environment and FEniCS version info
          command: |
            echo $USER $HOME $PWD $PATH $LD_LIBRARY_PATH $CMAKE_PREFIX_PATH
            python3 -c "import ffc; print(ffc.git_commit_hash(), ffc.ufc_signature())"
            python3 -c "import dolfin; print(dolfin.git_commit_hash())"

      - run:
          name: Install xalbrain
          command: |
            sudo python3 -m pip install .

      - run:
          name: Import xalbrain first time (JIT)
          command: |
            python3 -c "import xalbrain"

      - run:
          name: Unit tests
          command: |
              python3 -W ignore:DeprecationWarning -m pytest -v -n 4 test/unit
