version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/stable
        user: fenics
        environment:
          LD_LIBRARY_PATH: /home/fenics/local/lib
          CMAKE_PREFIX_PATH: /home/fenics/local
    working_directory: /home/fenics/xalbrin

    steps:
       - checkout
       - run: echo "hello world"
