version: 2

dependencies:
  pre:

jobs:
  build:

    docker:
      - image: quay.io/fenicsproject/stable
        user: fenics
        environment:
          LD_LIBRARY_PATH: /home/fenics/local/lib
          CMAKE_PREFIX_PATH: /home/fenics/local
    working_directory: /home/fenics/xalbrain

    steps:
      - checkout

      # - run:
      #     name: install python3.6
      #     command: |
      #       sudo add-apt-repository -y ppa:jonathonf/python-3.6
      #       sudo apt-get update
      #       sudo apt-get install -y python3.6
      #       sudo apt install -y python3.6-dev
      #       sudo apt install -y python3.6-venv
      #       wget https://bootstrap.pypa.io/get-pip.py
      #       sudo python3.6 get-pip.py

      - run:
 	  name: install python3-venv 
	  command: |
	    sudo apt-get install -y python3-venv

      - run:
          name: install-python-requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install pytest --upgrade
            pip3 install -Ur requirements-dev.txt

      - run:
          name: Environment and FEniCS version info
          command: |
            . venv/bin/activate
            echo $USER $HOME $PWD $PATH $LD_LIBRARY_PATH $CMAKE_PREFIX_PATH
            python3 -c "import ffc; print(ffc.git_commit_hash(), ffc.ufc_signature())"
            python3 -c "import dolfin; print(dolfin.git_commit_hash())"
  
      - run:
          name: Install xalbrain
          command: |
            . venv/bin/activate
            python3 setup.py install

      - run:
          name: Import xalbrain first time (JIT)
          command: |
            python3 -c "import xalbrain"
            . venv/bin/activate

      - run:
          name: Unit tests
          command: | 
            . venv/bin/activate
            python3 -m pytest -v test/unit
  
      - store_artifacts:
          path: /tmp/circle
          destination: build
  
      - store_test_results:
          path: /tmp/circle
