version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/stable
        user: fenics
        environment:
          LD_LIBRARY_PATH: /home/fenics/local/lib
          CMAKE_PREFIX_PATH: /home/fenics/local
    working_directory: /home/fenics/xalbrin

    steps:
      - checkout
      - run:
          name: Environment and FEniCS version info
          command: |
            echo $USER $HOME $PWD $PATH $LD_LIBRARY_PATH $CMAKE_PREFIX_PATH
            python3 -c "import ffc; print(ffc.git_commit_hash(), ffc.ufc_signature())"
            python3 -c "import dolfin; print(dolfin.git_commit_hash())"
  
      - run:
          name: Install FENaPack
          command: |
            pip3 install -v --user .


